### ISSUE TITLE
Add support for specifying versions per tool, including toolchain support (i.e. `latest`, `nightly`)

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/fuel.nix#6]
Currently we only provide a snapshot of `master` that is pinned by the current state of the flake inputs listed under the `flake.lock` file.

Ideally we should also provide every published release along with any extra toolchain releases provided by fuelup (e.g. nightly).

The [oxalica's rust-overlay](https://github.com/oxalica/rust-overlay) achieves this nicely. We should look to it for inspiration.

This might involve using some CI automation to maintain an index of all necessary source inputs for each release.

# TODO

- [x] Write a script that can be used to generate a manifest for each package. Each should contain a specific git commit, a pre-computed sha256 hash, the date and time it was created, etc.
    - [x] For published versions, use either git tags or releases from each repo.
    - [ ] For nightlies, use the git commit associated with each release: 
    - [x] Write all to a single `manifest` directory in a readable (for debugging), nix-serializable format like `rust-overlay`'s [here](https://github.com/oxalica/rust-overlay/tree/master/manifests).
- [x] Construct the `packages` set using the generated manifests.
